# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=250)),
                ('app_mail', models.CharField(max_length=250)),
                ('app_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_mail', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
